# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: report_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'report_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import transaction_service_pb2 as transaction__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14report_service.proto\x12\x06report\x1a\x19transaction_service.proto\"6\n\x14MonthlyReportRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05month\x18\x02 \x01(\t\"u\n\x15MonthlyReportResponse\x12\x14\n\x0ctotal_income\x18\x01 \x01(\x01\x12\x16\n\x0etotal_expenses\x18\x02 \x01(\x01\x12.\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x18.transaction.Transaction\"5\n\x13\x45xportReportRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05month\x18\x02 \x01(\t\",\n\x14\x45xportReportResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x32\xa8\x01\n\rReportService\x12L\n\rMonthlyReport\x12\x1c.report.MonthlyReportRequest\x1a\x1d.report.MonthlyReportResponse\x12I\n\x0c\x45xportReport\x12\x1b.report.ExportReportRequest\x1a\x1c.report.ExportReportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'report_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONTHLYREPORTREQUEST']._serialized_start=59
  _globals['_MONTHLYREPORTREQUEST']._serialized_end=113
  _globals['_MONTHLYREPORTRESPONSE']._serialized_start=115
  _globals['_MONTHLYREPORTRESPONSE']._serialized_end=232
  _globals['_EXPORTREPORTREQUEST']._serialized_start=234
  _globals['_EXPORTREPORTREQUEST']._serialized_end=287
  _globals['_EXPORTREPORTRESPONSE']._serialized_start=289
  _globals['_EXPORTREPORTRESPONSE']._serialized_end=333
  _globals['_REPORTSERVICE']._serialized_start=336
  _globals['_REPORTSERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
